/**
 * Stable machine-readable error codes returned in the API error envelope.
 * Clients branch on `code`, never on `message`.
 */
export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  AI_BLOCKED_BY_POLICY: 'AI_BLOCKED_BY_POLICY',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  MFA_REQUIRED: 'MFA_REQUIRED',
  INTERNAL: 'INTERNAL',
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
