import type { CompletionRequest, CompletionResponse, LlmProvider } from '../types';

/**
 * Deterministic provider for local development, CI and red-team tests.
 * Produces schema-valid JSON so the whole human-in-the-loop flow can be
 * exercised without any external AI account. It also honours a few magic
 * phrases so tests can force specific behaviours:
 *   "__MOCK_INVALID_JSON__"  → returns malformed output once
 *   "__MOCK_REFUSE__"        → simulates a provider refusal
 *   "__MOCK_TIMEOUT__"       → never resolves (caller's timeout fires)
 */
export class MockProvider implements LlmProvider {
  readonly name = 'mock';
  readonly isExternal = false;
  private invalidServed = new Set<string>();

  async complete(req: CompletionRequest): Promise<CompletionResponse> {
    // Strip the untrusted-input wrapper so simple label lookups below work.
    const user = req.messages
      .map((m) => m.content)
      .join('\n')
      .replace(/<\/?untrusted_patient_input>\n?/g, '')
      .replace(/\(The following is [^)]*\)\n?/g, '');
    const key = req.messages[0]?.content ?? '';
    if (user.includes('__MOCK_TIMEOUT__')) return new Promise(() => undefined);
    if (user.includes('__MOCK_REFUSE__')) return { text: "I can't help with that.", model: 'mock-1', refused: true };
    if (user.includes('__MOCK_INVALID_JSON__') && !this.invalidServed.has(key)) {
      this.invalidServed.add(key);
      return { text: 'Sure! Here is the note: { "soapNote": ', model: 'mock-1' };
    }

    const firstLine = (label: string) => {
      const m = user.match(new RegExp(`${label}[^\\n]*\\n([^\\n]+)`));
      return m?.[1]?.trim() ?? '';
    };
    const hasEmergency = /chest pain|can'?t breathe|suicid|bleeding heavily|stroke/i.test(user);

    let payload: unknown;
    switch (req.workflow) {
      case 'CLINICAL_NOTE':
        payload = {
          soapNote: {
            subjective: `Patient reports: ${firstLine('Intake summary') || 'see intake'}. Clinician notes: ${firstLine('Clinician notes') || '(none)'}.`,
            objective: 'Vital signs and examination findings not documented in the provided context.',
            assessment: 'Presentation consistent with the reported complaint; differential to be confirmed by clinician. No final diagnosis made.',
            plan: 'Plan to be confirmed by clinician. Consider follow-up if symptoms persist or worsen.',
          },
          structuredData: { chiefComplaint: firstLine('Intake summary') || '', symptoms: [], medications: [], allergies: [], followUp: 'As directed by clinician' },
          codingSuggestions: { icd10: [], snomed: [], confidence: 0.3 },
          missingInformation: ['Vital signs', 'Examination findings'],
          uncertainty: 'Draft generated by mock provider for development; low confidence.',
          safetyFlags: hasEmergency ? ['possible_red_flag_symptom'] : [],
          confidence: 0.55,
        };
        break;
      case 'PATIENT_MESSAGE_DRAFT':
        payload = hasEmergency
          ? {
              suggestedResponse:
                'Thank you for your message. Some of what you describe needs urgent attention. Please contact emergency services or go to your nearest emergency department now. Our team has been alerted.',
              tone: 'urgent-supportive',
              readingLevel: 'grade-6',
              escalationRecommended: true,
              escalationReason: 'Message describes potentially life-threatening symptoms.',
              urgencyLevel: 'EMERGENCY',
              needsClinicianReview: true,
            }
          : {
              suggestedResponse:
                'Thank you for your message. A member of your care team has read it and will get back to you with next steps. If your symptoms get worse, please let us know straight away.',
              tone: 'professional',
              readingLevel: 'grade-6',
              escalationRecommended: false,
              escalationReason: null,
              urgencyLevel: 'LOW',
              needsClinicianReview: true,
            };
        break;
      case 'INTAKE_SUMMARY':
        payload = {
          summary: `Patient submitted an intake form. Reason for visit: ${firstLine('Appointment reason') || 'not stated'}.`,
          missingInformation: ['Symptom duration'],
          redFlags: hasEmergency ? ['possible_emergency_symptom'] : [],
          urgencyLevel: hasEmergency ? 'EMERGENCY' : 'LOW',
          structuredFields: { chiefComplaint: firstLine('Appointment reason') || '', duration: '', medications: [], allergies: [] },
        };
        break;
      case 'PATIENT_EDUCATION':
        payload = {
          title: `About ${firstLine('Topic approved') || 'your condition'}`,
          explanation: 'This is general information written in plain language. Your care team will confirm what applies to you.',
          careInstructions: ['Rest and drink fluids.', 'Follow the plan your care team gave you.'],
          warningSigns: ['Symptoms that get much worse quickly', 'Trouble breathing', 'Severe pain'],
          followUpGuidance: 'Contact your care team if you have questions or your symptoms change.',
          disclaimer: 'This is general information and not a substitute for advice from your care team.',
          readingLevel: 'grade-6',
        };
        break;
      case 'MESSAGE_TRIAGE':
        payload = {
          intent: /appointment|book|reschedule/i.test(user) ? 'appointment_request' : /medication|prescription|tablet|dose/i.test(user) ? 'medication_question' : /bill|invoice|payment/i.test(user) ? 'billing' : /pain|fever|symptom|feel/i.test(user) ? 'symptom_report' : 'other',
          urgencyLevel: hasEmergency ? 'EMERGENCY' : 'LOW',
          redFlags: hasEmergency ? ['possible_emergency_symptom'] : [],
          suggestedRoute: hasEmergency ? 'clinician' : 'nurse',
          summary: 'Patient message classified by mock provider.',
          sentiment: hasEmergency ? 'distressed' : 'neutral',
        };
        break;
      default:
        payload = {};
    }
    const text = JSON.stringify(payload);
    return { text, model: 'mock-1', inputTokens: Math.ceil(user.length / 4), outputTokens: Math.ceil(text.length / 4) };
  }
}
